from __future__ import annotations

import shutil
import zipfile
from pathlib import Path
from xml.etree import ElementTree

import yaml

from command_center.job_search.achievement_bank import ensure_bank
from command_center.job_search.config import data_root, ensure_data_dirs, load_config


EVIDENCE_STUBS = {
    "jpmorgan.md": "# JPMorgan Evidence\n\nCurated notes for JPMorgan analytics, ML, data engineering, experimentation, and leadership claims.\n",
    "driveline.md": "# Driveline Evidence\n\nCurated notes for Driveline Baseball sports science, EMG, biomechanics, time-series, and modeling claims.\n",
    "world_model_sports.md": "# World Model Sports Evidence\n\nWorld Model Sports LLC / Hoops World Model experience source.\n\n- Founder & CEO / Principal Data Scientist, 2026 - Present.\n- Basketball intelligence platform focused on NBA player valuation, contract efficiency, roster strategy, forecasting, graph/network analysis, and explainable decision-support.\n- Use `Founder & CEO` for leadership/startup/product/sports strategy roles.\n- Use `Founder / Principal Data Scientist` for IC data scientist, analytics engineer, ML engineer, and hands-on roles.\n",
    "betts_basketball.md": "# Betts Basketball Evidence\n\nCurated notes for basketball analytics engineering, modeling, APIs, dashboards, and product work.\n",
    "sports_projects.md": "# Sports Projects Evidence\n\nCurated notes for Marlins hackathon, NBA player value forecasting, computer vision, salary modeling, and sports analytics projects.\n",
    "education.md": "# Education Evidence\n\n- PhD in Computer Science, Florida Atlantic University, Jan 2026 - 2028 estimated.\n- M.S. Data Science, University of West Florida, May 2023 - May 2025.\n- B.A.S. Economics, Valencia College, May 2019 - May 2023.\n",
}


def extract_docx_text(path: Path) -> list[str]:
    if not path.exists():
        return []
    with zipfile.ZipFile(path) as archive:
        xml = archive.read("word/document.xml")
    root = ElementTree.fromstring(xml)
    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    paragraphs: list[str] = []
    for para in root.findall(".//w:p", ns):
        text = "".join(t.text or "" for t in para.findall(".//w:t", ns)).strip()
        if text:
            paragraphs.append(text)
    return paragraphs


def _write_if_missing(path: Path, content: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def _write_yaml_if_missing(path: Path, data: dict) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    return True


def ingest_profile() -> dict:
    cfg = load_config()
    root = data_root(cfg)
    ensure_data_dirs(root)

    report: dict[str, object] = {
        "data_root": str(root),
        "created": [],
        "updated": [],
        "docx_paragraphs": 0,
        "achievement_count": 0,
    }

    source_docx = root / "Master_Resume_Bullet_Bank.docx"
    profile_docx = root / "profile" / "Master_Resume_Bullet_Bank.docx"
    if source_docx.exists() and not profile_docx.exists():
        profile_docx.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source_docx, profile_docx)
        report["created"].append(str(profile_docx))  # type: ignore[union-attr]

    paragraphs = extract_docx_text(profile_docx)
    report["docx_paragraphs"] = len(paragraphs)

    bank_path = root / "profile" / "achievement_bank.yml"
    bank_existed = bank_path.exists()
    bank = ensure_bank(bank_path)
    report["achievement_count"] = len(bank.achievements)
    if bank_existed:
        report["updated"].append(str(bank_path))  # type: ignore[union-attr]
    else:
        report["created"].append(str(bank_path))  # type: ignore[union-attr]

    for name, content in EVIDENCE_STUBS.items():
        if _write_if_missing(root / "evidence" / name, content):
            report["created"].append(str(root / "evidence" / name))  # type: ignore[union-attr]

    profile_files = {
        "resume_variants.yml": {
            "schema_version": "command-center.job-search.resume-variants.v1",
            "variants": cfg.resume_variants,
            "notes": "Detailed per-variant controls are generated by the MVP selector and can be expanded manually.",
        },
        "job_targets.yml": {
            "schema_version": "command-center.job-search.targets.v1",
            "highest_priority": [
                "Product Data Scientist",
                "Applied Data Scientist",
                "Senior Analytics Engineer",
                "Analytics Engineer",
                "Sports Data Scientist",
                "Basketball Data Scientist",
                "Data Scientist, Experimentation",
                "Data Architecture Manager",
            ],
            "locations": ["Remote US", "Florida", "Phoenix hybrid"],
        },
        "writing_style.yml": {
            "schema_version": "command-center.job-search.writing-style.v1",
            "resume": "Concise, evidence-backed, technical, impact-oriented.",
            "cover_letter": "Direct, role-specific, no generic enthusiasm filler.",
        },
        "manual_only_rules.yml": {
            "schema_version": "command-center.job-search.manual-rules.v1",
            "manual_portals": cfg.automation.manual_portals,
            "manual_phrases": cfg.automation.manual_phrases,
            "blocked_actions": cfg.automation.blocked_actions,
        },
        "claim_policy.yml": {
            "schema_version": "command-center.job-search.claim-policy.v1",
            "require_achievement_id": True,
            "require_evidence_file": True,
            "reject_low_confidence_by_default": True,
            "unsupported_keywords": "report_as_gap_do_not_stuff",
        },
        "application_question_policy.yml": cfg.application_questions.model_dump(mode="json"),
    }
    for name, data in profile_files.items():
        if _write_yaml_if_missing(root / "profile" / name, data):
            report["created"].append(str(root / "profile" / name))  # type: ignore[union-attr]

    inbox_dir = root / "profile" / "inbox"
    inbox_dir.mkdir(parents=True, exist_ok=True)
    pending_inbox = sorted(p.name for p in inbox_dir.iterdir() if p.is_file())
    report["pending_inbox_files"] = pending_inbox
    if pending_inbox:
        report["inbox_hint"] = (
            "New achievements found in profile/inbox/ are not auto-merged: turning "
            "freeform text into achievement_bank.yml entries needs editorial judgment "
            "(evidence file, confidence, resume_safe, per-variant bullet wording). Ask "
            "Claude Code or Codex to structure these files into achievement_bank.yml "
            "following RESUME_CLAIM_POLICY.md, then remove them from inbox/."
        )

    report_path = root / "profile" / "profile_ingest_report.yml"
    report_path.write_text(yaml.safe_dump(report, sort_keys=False), encoding="utf-8")
    report["report_path"] = str(report_path)
    return report

