"""Canonical work graph — one durable WorkItem, projected onto many boards as
WorkPlacements, connected by typed WorkEdges. A todo that belongs to three
boards is ONE work item with three placements, never three unrelated cards.

The identity + placement + edge model is the durable spine everything else
(deep links, chat receipts, the Work Map) hangs off. Blocking-style edges are
kept acyclic; informational edges may cycle. Links are generated by the backend,
never assembled by the browser.
"""
from .schemas import (
    ACYCLIC_RELATIONS,
    CYCLE_OK_RELATIONS,
    WORK_ITEM_KINDS,
    ResourceLink,
    WorkEdge,
    WorkEvent,
    WorkGraph,
    WorkItem,
    WorkPlacement,
)
from .ledger_store import LedgerWorkGraphStore
from .service import WorkGraphError, WorkGraphService
from .store import InMemoryWorkGraphStore

__all__ = [
    "ACYCLIC_RELATIONS",
    "CYCLE_OK_RELATIONS",
    "WORK_ITEM_KINDS",
    "ResourceLink",
    "WorkEdge",
    "WorkEvent",
    "WorkGraph",
    "WorkItem",
    "WorkPlacement",
    "WorkGraphError",
    "WorkGraphService",
    "InMemoryWorkGraphStore",
    "LedgerWorkGraphStore",
]
